<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 cap-mx-switch-15x33.glb -t -u -T --draco draco
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense, useDraco, Outlines } from '@threlte/extras';
	import { base } from '$app/paths';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			['switch-cap-15x33']: THREE.Mesh;
		};
		materials: {};
	};

	const gltf = suspend(
		useGltf<GLTFResult>(base + '/cap-mx-switch-15x33-transformed.glb', {
			dracoLoader: useDraco(base + '/draco/')
		})
	);
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
    <T.Mesh scale={0.1}>
      <T is={gltf.nodes['switch-cap-15x33'].geometry} />
      <T.MeshToonMaterial color="#550000" />
      <Outlines color="#ff2222" width={2} angle={1} />
    </T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
