<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 cap-mx-switch-15x33.glb -t -u -T --draco draco
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, useTask, type Props } from '@threlte/core';
	import { useGltf, useSuspense, useDraco, Outlines, useCursor } from '@threlte/extras';
	import { base } from '$app/paths';
	import { spring } from '$lib/Utils';

	const { onPointerEnter, onPointerLeave } = useCursor();

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
    interactive = $bindable(true),
    color = '#4c0519',
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
    interactive?: boolean;
    color?: string;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			['switch-cap-15x33']: THREE.Mesh;
		};
		materials: {};
	};

	const gltf = suspend(
		useGltf<GLTFResult>(base + '/cap-mx-switch-15x33-transformed.glb', {
			dracoLoader: useDraco(base + '/draco/')
		})
	);

	let movementSpring = spring<number>(0, 0.2, 0.8);
	let movement = $state(0);

	useTask((delta) => {
		movement = movementSpring.update(delta);
	});

	function onPointerDown(evt: any) {
    if (!interactive) return;
    evt.stopPropagation();
		console.log('onPointerDown');

		movementSpring.set(-0.2);
		setTimeout(() => {
			movementSpring.set(0);
		}, 200);
	}

	function onPointerUp(evt: any) {
    if (!interactive) return;
    evt.stopPropagation();
		console.log('onPointerUp');

		movementSpring.set(0);
	}
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			scale={0.1}
			position.y={movement}
			onpointerdown={(evt: any) => {
				onPointerDown(evt);
			}}
			onpointerleave={() => {
				// sizeSpring.set(1.5);
				onPointerLeave();
			}}
			onpointerenter={() => {
				// sizeSpring.set(1.6);
				onPointerEnter();
			}}
			ontouchstart={(evt: any) => {
				onPointerDown(evt);
			}}
			ontouchend={(evt: any) => {
				onPointerUp(evt);
			}}
		>
			<T is={gltf.nodes['switch-cap-15x33'].geometry} />
			<T.MeshToonMaterial color={color} />
			<Outlines color="white" width={2} angle={1} />
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
